services:
  server:
    image: adityaa72/ebook-mern-server
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      - cdn_private_files:/app/private
      - cdn_public_files:/app/files
    env_file:
      - .env

volumes:
  cdn_private_files:
  cdn_public_files:
